eureka:
  instance:
    preferIpAddress: true # 컨테이너 기반 환경에서 DNS 엔트리가 임의로 생성한 호스트 이름을 할당하므로 IP기반이 더 적합
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/

keycloak:
  realm: spcloud-realm
  auth-server-url: http://localhost:8080/auth # issuer url이 realm url과 같아야 함
  ssl-required: external
  resource: spcloud
  credentials:
    secret: 5e785f8e-ad9f-4c8d-bcae-948a87324c17
  use-resource-role-mappings: true
  bearer-only: true
