spring:
  datasource:
    hikari:
      max-lifetime: 1800000 # (ms), default
      connection-timeout: 10000
      validation-timeout: 10000
      driver-class-name: org.postgresql.Driver
    url: ${spring.datasource.hikari.jdbc-url}
    driver-class-name: ${spring.datasource.hikari.driver-class-name}
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      org.hibernate.envers.audit_table_suffix: _HIS
      org.hibernate.envers.modified_flag_suffix: _CHANGED
      org.hibernate.envers.modified_column_naming_strategy: improved
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 10
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      mode: never
