spring:
  application:
    name: organization-service
  config:
    import: "optional:configserver:http://configserver:8071"
  cloud:
    config:
      name: organization-service
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 10
        multiplier: 2
      request-connect-timeout: 2000
      request-read-timeout: 10000

logging:
  level:
    org.springframework.security: DEBUG
