server:
  port: 8071

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/dlxotn216/spring-cloud-microservices.git
          search-paths: configs
          default-label: master
        vault:
          port: 8200
          host: 127.0.0.1
          kv-version: 2
          backend: licensing-service
          order: -10
          token: myroot
          scheme: http
          authentication: token

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web.client: TRACE
