spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://configserver:8071"
  cloud:
    config:
      uri: http://configserver:8071
      name: eureka-server
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 10
        multiplier: 2
      request-connect-timeout: 2000
      request-read-timeout: 10000
